--
-- Contenu de la table `tab_experiences`
--

INSERT INTO `tab_experiences` (`id`, `ordre`, `titre_experience`, `commentaire_titre`, `debut`, `fin`, `employeur`, `fonction`, `secteur`, `fonctionnel`, `realisation`, `language`, `applicatif`, `develloppement`, `bdd`, `meta`) VALUES
(1, 0, 'Créer des produits pour la vidéo location', '', '1998', '2004', 'Energie Video', 'Chargé logiciel', 'Divertissement', '- Etude du besoin et proposition de solution<br>- Prototype<br>', '- Développement<br>- Industrialisation<br>', 'VB', '', 'Visual Studio', 'MySql', ''),
(2, 10, 'Diagnostique sommeil', '', '2004', '2007', 'ILLEO', 'Chargé de dévellopement', 'Médical', '- Etude du besoin et proposition de solution<br>- Prototype<br>', '- Développement<br>- Industrialisation<br>', 'HTML, PHP', 'FTP, Apache', 'NotePad++', 'MySql', ''),
(3, 20, 'SCA-CPE, FRANCETELECOM', 'Application de médiation ADSL', 'Juin 2007', 'Août 2008', 'CGI', 'Concepteur Technique et fonctionnelle', 'Télécommunication', '- Chiffrage<br>', '- Réalisation de spécifications techniques (DAL-CD)<br>- Développement et test<br>- Optimisation des performances<br>', 'HTML, Java, J2EE, JSP, Spring, webservices, Axis, Hibernate, Struts, XML, SQL, Shell', 'Unix, MQ Series,Weblogic, Tomcat,CVS', 'Eclipse', 'Oracle', ''),
(4, 30, 'MORNING, FRANCETELECOM', 'Projet d’inventaire réseaux télécom', 'Août 2008', 'Février 2009', 'CGI', 'Analyste-programmeur', 'Télécommunication', '- Chiffrage<br>', '- Réalisation de spécifications techniques<br>- Développement et test<br>- Optimisation, correctifs.<br>- Migration par réconciliation Netcracker<br>- Migration par scritps PL/SQL<br>', 'Shell, SQL, PL / SQL', 'Linux, Netcracker', 'NotePad++', '', ''),
(5, 40, 'ERECA, SANOFI', 'Gestion Ressources humaines des chaines de production', 'Février 2009', 'Août 2009', 'CGI', 'Concepteur Technique et fonctionnelle', 'Pharmaceutique', '- Etude du besoin et proposition de solution<br>- Rédaction des spécifications fonctionnelles<br>- Chiffrage<br>', '- Réalisation de spécifications techniques<br>- Développement et test<br>- Optimisation des performances<br>', 'Java J2EE : Struts, Spring, Hibernate, Ajax', 'Tomcat', 'Eclipse, Maven, CheckStyle', 'Oracle', ''),
(6, 50, 'LRF, RIOTINTO', 'Mis en place de solution pour le laboratoire de recherche', 'Août  2009', 'Décembre 2010', 'CGI', 'Concepteur Technique et fonctionnelle', 'Métallurgie', '- Etude du besoin et proposition de solution<br>- Rédaction des spécifications fonctionnelles<br>- Prototype<br>', '- Réalisation de spécifications techniques<br>- Développement et test<br>- Optimisation des performances<br>', 'VB 6, .NET, Java', 'Excel', 'Visual Basic 6, Visual basic.net, Jdev', 'Acces, Oracle, MS Sql Server', ''),
(7, 60, 'MFA, STMICRO ', 'Automatisation des chaines de production', 'Septembre 2009', 'Mars 2010', 'CGI', 'Analyste-programmeur', 'Fonderie', '- Rédaction des spécifications fonctionnelles<br>- Chiffrage<br>', '- Réalisation de spécifications techniques<br>- Développement et test<br>- Optimisation, correctifs<br>', 'C Plus', 'Unix ', 'Eclipse, FACTORYworks, AMA', 'Unix (C++), Eclipse, FACTORYworks, AMA', ''),
(8, 70, 'PIMS, LAFARGE', 'Outil de super-gestion d’un serveur Excel', 'Septembre 2010', 'Janvier 2011', 'CGI', 'Concepteur Technique et fonctionnel', 'Cimentrie', '- Etude du besoin et proposition de solution<br>- Rédaction des spécifications fonctionnelles<br>- Prototype<br>- Chiffrage<br>', '- Réalisation de spécifications techniques<br>- Développement et test<br>- Réalisation d’un outil de gestion de processus Excel inter-serveur.<br>- Optimisation des performances<br>', '.NET : ASP.NET, C#, webservices, SQL, Macro Excel', 'Excel', 'ISS, Visual Studio.net, Plsql Develloper', 'Oracle', ''),
(9, 80, 'DISE SOUTIEN, ORANGE', 'Expertise du soutient niveau trois', 'Mai 2011', 'Maintenant', 'CGI', 'Analyste', 'Télécomunication', '- Contrôle qualité.<br>- Audite.<br>- Analyse des spécifications fonctionnelles.<br>', '- Réalisation de mode opératoire.<br>- Industrialisation de processes.<br>- Réalisation d’un outil de gestion.<br>- Optimisation des performances.<br>', 'IBM AS400 (RPG, CL, SYNON), SQL', 'CFT, MQ Series', 'ARCADE', 'SQL', ''),
(10, 90, 'ODA, CGI', 'Outils d''audit automatique et de gestion', 'Février 2012', 'Maintenant', 'CGI', 'Chargé de projet', 'Services', '- Etude du besoin et proposition de solution.<br>- Rédaction de l''architecture fonctionelle.<br>- Réalisation des spécifications fonctionelles.<br>- Organise le travail par phase, définit les priorités.<br>- Pilote des réunions.<br>', '- Réalisation de spécifications techniques.<br>- Développement et test.<br>- Optimisation, correctifs.<br>', 'PHP, Javascript, AJAX, SQL, CSS, HTML5', 'FTP, Apache', 'NotePad++', 'Mysql', 'chef projet, pilote, charger de projet'),
(11, 81, 'Formation : Framework Spring ', 'Niveau expert', 'Mai 2011', 'Mai 2011', 'CGI', 'Développeurs Java', 'Technique', '- VUE D’ENSEMBLE<br>Pourquoi Spring est-il apparu (ou  les EJB 1.x/2.x et leurs problèmes) ?<br>L’injection de contrôle (ou  injection de dépendances) <br>La programmation orientée aspects <br>Bilan des problèmes que Spring entend résoudre <br><br>- INTERCONNEXION DE BEANS <br>Connexions minimales (par constructeur et/ou propriétés) <br>Auto connexion et bean factory <br>Éditeurs de propriétés <br><br>- INTRODUCTION À LA PROGRAMMATION AOP DANS SPRING <br>Une introduction rapide <br>Création d’advice, de pointcuts et d’introductions <br>Utilisation du ProxyFactoryBean <br><br>- SPRING ET L\\’ACCÈS AUX DONNÉES <br>Le pattern DAO <br>Spring et JDBC <br>Spring et les outils ORM (Hibernate, particulièrement) <br>Spring et la gestion des transactions <br><br>- SPRING ET LE WEB <br>Une introduction minimale à Spring MVC <br>Intégration d’autres Frameworks <br>Etude des cas de Struts et de JFC <br><br>- INTRODUCTION AUX AUTRES SERVICES <br>Spring remoting <br>JNDI et Quartz <br>Pour bien démarrer : Spring IDE et AppFuse <br>', 'NA.', 'JAVA', 'Tomcat', 'Eclipse', 'Oracle', 'Expert Technique'),
(12, 100, 'Formation : .NET/WPF ', 'Niveau expert', 'Mai 2013', 'Mai 2013', 'CGI', 'Développeurs  .Net', 'Technique', '- Architecture et vue d’ensemble<br>Présentation de la plateforme .NET<br>Présentation du framework .NET<br> Visual Studio 2010<br><br>- Programmation C#<br> Bonnes pratiques de développement<br>Les bases du C#<br>POO<br>C# et POO<br><br>- Asp.net<br>La programmation Web<br>Initialiser un formulaire web<br>Les évènements primaires d’une page web<br>Gestion des valeurs postées<br>Contrôles asp.net<br>Gestion des données de portée Application<br>Gestion des données de portée Session<br>Gestion du PostBack<br> Gestion du ViewState d’une page ASPX<br>Transfert et Redirection de page<br>Les contrôles utilisateurs<br>Les masterPage<br><br>- ADO.net<br>Accès aux données via ADO.net<br><br>- Web Services<br>Définition, création et invocation<br>Déploiement <br><br>- WPF<br>', 'NA.', 'C#', '.Net', 'Visual Studio 2010', 'Mysql', ''),
(13, 110, 'Formation : Devenir Agile avec Scrum', 'Agilité', 'Octobre 2013', 'Octobre 2013', 'CGI', 'Chargé de projet', 'Projet', '- Contenu de la séance<br>Qu’est ce que l’AGILITE ?<br>L’approche SCRUM<br>L’itération 0 ou le pré-game<br>L’itération - déroulement<br>La collaboration dans l’équipe<br>Les bonnes pratiques<br>La fin de projet<br>L’essentiel<br>Mise en situations afin de mieux appréhender la méthodologie et les points clés<br><br>- Les +<br>Cet atelier développe vos talents<br>Elaboration des user stories<br>Création d’un backlog de produit<br>Création d’un backlog d’itération<br>Pilotage d’un projet AGILE<br>Amélioration continue<br>', 'NA.', 'Scrum', 'NA.', 'NA.', 'NA.', ''),
(14, 120, 'Formation : Kanban, la force du flux', 'Agilité', 'Novembre 2013', 'Novembre 2013', 'CGI', 'Chargé de projet', 'Projet', '- Contenu de la séance<br>Atelier ludique : Casino Game *<br>Présentation dynamique des concepts découverts lors du jeu<br>Illustration avec des cas d’utilisation<br>', 'NA.', 'NA.', 'NA.', 'NA.', 'NA.', ''),
(15, 130, 'Formation : ATDD - Développement piloté par les tests d’acceptance', 'Agilité', 'Janvier 2014', 'Janvier 2014', 'CGI', 'Expert Technique / Pilote', 'Projet', '- Contenu de la séance<br>Présentation de l’ATDD<br>Définition et périmètre<br>Démarche<br>Critères d’acceptance et Story Tests<br>Outillage<br>Cas pratique avec l’outil FitNesse : « The Calc »<br><br>- Les +<br>Cet atelier développe vos talents<br>Mise en place d’une démarche de tests<br>Elaboration de critères d’acceptance<br>Création de Story Tests<br>Vue d’ensemble sur l’outillage de tests<br>Utilisation de l’outil FitNesse, framework de tests "fonctionnels" pour l''intégration continue<br>Mise en place de méthodologies innovantes<br>', 'NA.', 'JAVA', 'FitNesse, framework', 'Eclipse', 'NA.', ''),
(16, 101, 'Framework Agile : ODA', 'Création d''un framework agile home made', 'Juin 2013', 'Maintenant', 'Libre d''utilisation', 'Architecte', 'Technique', 'NA.', '- Multi-platforme<br>Browsers<br>IOS<br>Android<br>BB<br>W7<br><br>- Webapp<br>HTML 4/5<br>CSS 2/3<br>Javascrip<br>Ajax<br><br>JQuery<br>JQueryMobile<br>JQunit<br>PhoneGap<br>Highchart<br>Datatable<br><br>- Rest<br>PHP 5<br>Python<br><br>- BD<br>Mysql<br>Oracle<br>Couchbase<br>', 'SQL,NoSQL,HTML,CSS,Javascript,PHP,Python', 'Jquery,JqueryMobile,PhoneGap,JQunit,Highchart,Datatable', 'NetBeans', 'Oracle,Mysql,Couchbase', ''),
(17, 102, 'NOA, FT', 'Outils de ticketing', 'Septembre 2013', 'Maintenant', 'CGI', 'Expert technique / Pilote', 'Soutient', '- Etude de besoin<br>- Proposition de solution<br>- Architecture<br>- Soutenabilité<br>', '- Pilotage l''équipe en charge de la solution<br>-Responsable technique<br>- Responsable de l''intégration continue<br>- Responsable TDD<br>- Responsable Scrum<br>', 'FW ODA, SQL,NoSQL,HTML,CSS,Javascript,PHP,Python', 'FW ODA, Jquery,JqueryMobile,PhoneGap,JQunit,Highchart,Datatables', 'NetBeans', 'Mysql,Couchbase', ''),
(18, 121, 'INDIGO, CGI', 'Outils de management projet', 'Novembre 2013', 'Maintenant', 'Libre d''utilisation', 'Expert technique / Pilote', 'Soutient', '- Etude de besoin<br>- Proposition de solution<br>- Architecture<br>- Soutenabilité<br>- Suivi hebdomadaire<br>-Gestion de congés<br>-Reporting<br>', '- Pilotage l''équipe en charge de la solution<br>-Responsable technique<br>- Responsable de l''intégrationcontinue<br>- Responsable TDD<br>- Responsable Scrum<br>', 'FW ODA, SQL,NoSQL,HTML,CSS,Javascript,PHP,Python', 'FW ODA, Jquery,JqueryMobile,PhoneGap,JQunit,Highchart,Datatables', 'NetBeans', 'Mysql,Couchbase', '');

--
-- Contenu de la table `tab_menu`
--

INSERT INTO `tab_menu` (`id`, `Description`, `Description_courte`, `id_categorie`, `Lien`) VALUES
(20, 'Expériences et compétences', 'Expériences et compétences', 1, 'page_passe.html'),
(21, 'Admin projet', 'Admin projet', 2, 'page_admin_projet.html'),
(22, 'Mon CV pdf', 'Mon CV pdf', 1, 'page_pj.html'),
(23, 'Mon souhait', 'Mon souhait', 1, 'page_futur.html'),
(24, 'Sand Box', 'Sand Box', 2, 'page_sandbox.html');

--
-- Contenu de la table `tab_menu_rangs_droit`
--

UPDATE `tab_menu_rangs_droit`
SET `id_menu` = CONCAT(`id_menu`,"22;23;")
WHERE `id_rang` in (99,30,20,10)
; 

UPDATE `tab_menu_rangs_droit`
SET `id_menu` = CONCAT(`id_menu`,"20;21;22;23;24;")
WHERE `id_rang` in (1)
; 